name: Publish Workflow Templates

on:
  push:
    branches: [ main ]
    paths:
      - 'workflow-templates/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate workflow templates
        run: |
          for file in workflow-templates/*.yml; do
            echo "Validating $file"
            yamllint "$file" || true
          done
